[package]
name = "benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
csv = "1.3.1"
csv-core = "0.1.12"
csv_lib = { git = "https://github.com/PTechSoftware/csv_lib.git" , branch = "v1.0.0"} #Like this cause i tested before update to crates io
