[package]
name = "usageexample"
version = "0.1.0"
edition = "2024"

#Other way of import the library
[dependencies]
csv_lib = { git = "https://github.com/PTechSoftware/csv_lib.git" , branch = "v1.0.0"}